name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        rustup update
        rustup target add wasm32-unknown-unknown
        cargo install trunk

    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic

    - name: Outdated
      run: |
        cargo install cargo-outdated && \
        cargo outdated -d2

    - name: Unused Deps
      run: |
        rustup update nightly && \
        cargo +nightly install cargo-udeps && \
        cargo +nightly udeps

    - name: Build
      run: trunk build --release

    - name: Run tests
      run: cargo test --verbose

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}

    #- name: Archive code coverage results
      #uses: actions/upload-artifact@v1
      #with:
        #name: code-coverage-report
        #path: cobertura.xml
